## EDA

### Problem Statement

##### A leading retail company wants to better understand its customers' shopping behavior in order to improve sales, customer satisfaction, and long-term loyalty. The management team has noticed changes in purchasing patterns across demographics, product categories, and sales channels (online vs. offline). They are particularly interested in uncovering which factors, such as discounts, reviews, seasons, or payment preferences, drive consumer decisions and repeat purchases.
##### You are tasked with analyzing the company's consumer behavior dataset to answer the following overarching business question:
##### "How can the company leverage consumer shopping data to identify trends, improve customer engagement, and optimize marketing and product strategies?"

In [67]:
import pandas as pd

In [68]:
df = pd.read_csv(r"C:\Users\SaiCharan T\Downloads\customer_shopping_behavior.csv")

In [69]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [70]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 835.9 KB

In [71]:
df.describe(include = 'all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [72]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [73]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [74]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [75]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [76]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [77]:
 # Create a column age_group
labels = ['Young Adult','Adult','Middle-age','Senior']
df['age_group'] = pd.qcut(df['age'], q=4,labels=labels)

In [78]:
df[['age','age_group']].head(10)

   age    age_group
0   55   Middle-age
1   19  Young Adult
2   50   Middle-age
3   21  Young Adult
4   45   Middle-age
5   46   Middle-age
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57   Middle-age

In [79]:
# Create column purchase_fequence_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [80]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [81]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [82]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [83]:
df = df.drop('promo_code_used', axis = 1)

In [84]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [85]:
pip install pyodbc pandas

Requirement already satisfied: pyodbc in c:\users\saicharan t\appdata\local\programs\python\python313\lib\site-packages (5.3.0)
Requirement already satisfied: pandas in c:\users\saicharan t\appdata\local\programs\python\python313\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\saicharan t\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\saicharan t\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\saicharan t\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\saicharan t\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [86]:
import pyodbc

# Build the connection string
conn_str = (
    r'Driver={ODBC Driver 17 for SQL Server};'
    r'Server=LAPTOP-UE0PPCAH;'
    r'Database=customer_behaviour;'
    r'Trusted_Connection=yes;'
)

# Establish connection
conn = pyodbc.connect(conn_str)

In [87]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\saicharan t\appdata\local\programs\python\python313\lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\users\saicharan t\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\saicharan t\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [88]:
from sqlalchemy import create_engine

engine = create_engine(
    "mssql+pyodbc://LAPTOP-UE0PPCAH/customer_behaviour?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

df.to_sql(
    name='Customer_Data',
    con=engine,
    if_exists='replace',   # replace / append
    index=False
)

print("Data Loaded Successfully")

Data Loaded Successfully

In [89]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in c:\users\saicharan t\appdata\local\programs\python\python313\lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\users\saicharan t\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\saicharan t\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   -------------------------- ------------- 1.8/2.8 MB 15.1 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 13.2 MB/s  0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [93]:
pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ------ --------------------------------- 2.9/17.7 MB 13.6 MB/s eta 0:00:02
   ------------- -------------------------- 5.8/17.7 MB 14.2 MB/s eta 0:00:01
   -------------------- ------------------- 8.9/17.7 MB 14.5 MB/s eta 0:00:01
   ---------------------------- ----------- 12.6/17.7 MB 15.2 MB/s eta 0:00:01
   ---------------------------------- ----- 15.5/17.7 MB 15.0 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 14.7 MB/s  0:00:01
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [96]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    port=3306,
    user="root",
    password="12345"
)

print("Connected:", conn.is_connected())

Connected: True

In [98]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\saicharan t\appdata\local\programs\python\python313\lib\site-packages (2.0.49)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in c:\users\saicharan t\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\saicharan t\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [100]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:12345@localhost:3306/customer_behaviour"
)

df.to_sql(
    name='customer_data',   # Table name in MySQL
    con=engine,
    if_exists='replace',    # replace existing table
    index=False
)

print("Data uploaded successfully!")

Data uploaded successfully!